"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MASTER.py']
DATA_FILES = ['ICON.png']
OPTIONS = {
    'packages': [],
    'iconfile': 'ICON.png'
    }

setup(
    name="UTS",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
